<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class GetSaleInvoice extends Model
{
    use HasFactory;

    protected $fillable = [
        'Vouch_Code',
        'Bill_No',
        'New_Bill_No',
        'Bill_Date',
        'Bill_Time',
        'Account_Code',
        'Account_Name',
        'Customer_Code',
        'Customer_Name',
        'Agent_Name',
        'Quantity',
        'Gross_Amount',
        'Net_Amount',
        'Total_Tax',
        'Branch_Name',
        'Branch_Code',
        'Currency_Name',
        'Tax_Region_Name',
        'Action_Code',
        'Type',
        'Branch_Short_Name',
        'Doc_Prefix',
        'Doc_Number',
        'RCU_Membership_Series',
        'RCU_Membership_Number',
        'Retail_Cust_Name',
        'Retail_Cust_Mobile_No',
        'Retail_Cust_Email_ID',
        'SO_Order_No',
        'SO_Order_Date',
        'SO_Party_Order_No',
        'SO_Party_Order_Date',
        'Credit_Note_Bill_Amount',
        'Gr_Number',
        'Gr_Date',
        'Order_No',
        'Order_Date',
        'Remarks1',
        'Cases',
        'Transport_Mode',
        'DNParty_Name',
        'CNParty_Name',
        'DISPParty_Name',
        'HANDParty_Name',
        'POSTParty_Name',
        'DN_Desc',
        'CN_Desc',
        'Display_Desc',
        'Challan_Date',
        'Challan_no',
        'DD_Chq',
        'DD_Chq_No',
        'DD_Chq_Amt',
        'GR_Number_2',
        'GR_Date_2',
        'Issue_Time',
        'Removal_Time',
        'Trans_Name',
        'Remarks2',
        'Remarks3',
        'Credit_Note_Amount',
        'ST_Branch_Code',
        'RCU_Create_Date',
        'Credit_Amount',
        'Cash_Amount',
        'Gift_Voucher_Amount',
        'Discount_Coupon_No',
        'Discount_Coupon_Amt',
        'Bill_Cancelled',
        'GST_EInvoice_IRN_No',
        'GST_EInvoice_QR_Image',
        'GST_EInvoice_Acknowledgement_No',
        'GST_EInvoice_Acknowledgement_Date',
        'GST_EWay_Bill_No',
        'GST_EWay_Bill_Date',
        'InvoicePDFLink',
        'TCS_Act_Name',
        'TCS_Percent',
        'TCS_Amount',
        'Credit_Card_Amount',
        'ListCreditCard',
        'ListItems',
        'Status',
        'Message',
        'LastGlobalModifyCode',
    ];
}
